# Generated by Django 6.0 on 2025-12-21 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('duty_rate', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='ShippingConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vat_rate', models.FloatField(default=0.175)),
                ('local_handling_fee', models.FloatField(default=25.0)),
                ('margin_rate', models.FloatField(default=0.15)),
            ],
        ),
        migrations.CreateModel(
            name='ShippingRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin_country', models.CharField(choices=[('USA', 'USA'), ('UK', 'UK')], max_length=5)),
                ('max_weight', models.FloatField()),
                ('price', models.FloatField()),
            ],
            options={
                'unique_together': {('origin_country', 'max_weight')},
            },
        ),
    ]
