# Generated by Django 6.0 on 2025-12-21 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shippingrate',
            options={'ordering': ['origin_country', 'min_weight']},
        ),
        migrations.AlterUniqueTogether(
            name='shippingrate',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='shippingrate',
            name='min_weight',
            field=models.FloatField(default=0.0),
        ),
    ]
